### ISSUE TITLE
Crates.io version LzfseEncoder doesn't compress anything, need new release

### ISSUE THREAD

**Issue by Dr-Emann** [shampoofactory/lzfse_rust#1]
## Version

Using lzfse_rust version 0.1.0 from crates.io

## Example Program

```rust
let data = vec![0; 1024 * 1024];
let mut encoded = Vec::new();

let mut encoder = lzfse_rust::LzfseEncoder::default();
let encoded_size = encoder.encode_bytes(&data, &mut encoded).unwrap();

println!("original size: {}", data.len());
println!("encoded size : {}", encoded_size);
```

## Expected behavior
Compressing 1 MiB of zeros should compress to much smaller than 1 MiB

## Actual behavior

Output of the above:

```
original size: 1048576
encoded size : 1048588
```

Compressing all zeros actually grows!

Using the ring encoder with

```rust
let data = vec![0; 1024 * 1024];
let mut encoded = Vec::new();

let mut encoder = lzfse_rust::LzfseRingEncoder::default();
encoder.encode(&mut &*data, &mut encoded).unwrap();

println!("original size: {}", data.len());
println!("encoded size : {}", encoded.len());
```

Outputs instead
```
original size: 1048576
encoded size : 759
```

Which seems like a more reasonable size for something so compressible.

**Comment by Dr-Emann** [comment]
This appears to be fixed in git, running the same but pulling from git with

```
lzfse_rust = { git = "https://github.com/shampoofactory/lzfse_rust.git" }
```

works as expected (and compresses to 755 bytes, yay)

I think a new release might be warranted.

**Comment by shampoofactory** [comment]
Hi. Thank you for the precise feedback and problem case. I can confirm the issue is as you've stated.

I had planned to review the new code changes before publishing. I'll endeavour to do this over the coming weekend, and assuming there are no issues, I'll rerun the extended tests and release a new version early next week.

**Comment by shampoofactory** [comment]
@shampoofactory TODO Add a zero byte array compressed size check test

Edit: done!

**Comment by shampoofactory** [comment]
The main branch is at a tentative version `0.2.0`. I still need to complete some long running tests, which I'll do overnight. If all is well, I'll push to `crates.io` tomorrow.

For the record, the bug is due to the `LzfseEncoder` selecting the wrong compression method. It's inadvertently falling back to `RAW` when `VN` or `FSE` would be the correct choice . It still decodes fine, but obviously it's not what we would want.

**Comment by shampoofactory** [comment]
Release `0.2.0` published.

**Comment by shampoofactory** [comment]
Running the above example program with `0.2.0` now compresses.

Source:
```Rust
fn main() {
    let mut data = vec![0; 1024 * 1024];
    data[0] = 1;
    let mut encoded = Vec::new();

    let mut encoder = lzfse_rust::LzfseEncoder::default();
    let encoded_size = encoder.encode_bytes(&data, &mut encoded).unwrap();

    println!("original size: {}", data.len());
    println!("encoded size : {}", encoded_size);
}
```

Output:
```
original size: 1048576
encoded size : 758
```
